### PR TITLE
chore: Limit the number of problems in the longer tests to 5

### LINKED ISSUE #140: Tests take too long
The tests are too extensive, they take too long to run. We should aim to only test with a few problems, for instance. If testing with all problems is desirable, we should look into splitting the tests.

### PR DESCRIPTION
**Pull request by abelsiqueira**
Related to #140, but does not close the issue. Tests still take too long.

### CODE REVIEW

**Review by tmigot — APPROVED** [review]
LGTM, thanks @abelsiqueira !
I guess if we have a benchmark regularly running that would replace this extensive test.

**Comment by abelsiqueira** [comment]
That makes sense. Maybe a more aggressive benchmark CI? Run every time, for instance?

**Comment by tmigot** [comment]
I think it is a good idea for such package

**Comment by abelsiqueira** [comment]
Spawned #146 for benchmark

**Comment by abelsiqueira** [comment]
Thanks for the review. Merging despite docs failure, since they are unrelated.

**Pull request merged**
